---
title: "Técnicas de Previsión"
author: "José, Oier y Marc"
date: "2025-12-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Estudio y Análisis Previo de la Serie

##Lectura de los Datos
```{r}
datos = read.csv("Turistas_Limpio.csv")
ts_total = ts(
  datos$Total,
  start = c(2015, 10),  # año, mes inicial
  frequency = 12        # mensual
)
```

##Visualización de la Serie Temporal
```{r}
plot(ts_total, 
     main = "Evolución de Turistas en España a lo largo de 10 años", 
     ylab = "Total", 
     xlab = "Año", 
     col = "blue")
```

##Descomposición de la Serie
### Visualización individual de cada componente
```{r fig.width=8, fig.height=6}
# Extraer componentes de la descomposición
descomp=stl(ts_total,s.window="periodic")
tendencia      = descomp$time.series[, "trend"]
estacionalidad = descomp$time.series[, "seasonal"]
ruido          = descomp$time.series[, "remainder"]

# Configuración del panel de gráficos
par(mfrow = c(3, 1), mar = c(4, 4, 3, 2))

# Tendencia
plot(tendencia,
     type = "l",
     col  = "blue",
     lwd  = 2,
     main = "Tendencia estimada de la serie",
     ylab = "Tendencia",
     xlab = "Tiempo")

# Estacionalidad
plot(estacionalidad,
     type = "l",
     col  = "darkgreen",
     lwd  = 2,
     main = "Componente estacional",
     ylab = "Estacionalidad",
     xlab = "Tiempo")

# Ruido
plot(ruido,
     type = "h",
     col  = "gray40",
     main = "Componente irregular (ruido)",
     ylab = "Residuo",
     xlab = "Tiempo")
abline(h = 0, col = "red", lty = 2)

# Restaurar layout
par(mfrow = c(1, 1))
```


##Visualización Varianza por Período
```{r,warning=FALSE}
library(zoo)

# Varianza móvil de 12 meses
var_movil = rollapply(ts_total, width = 12, FUN = var, align = "right", fill = NA)

# Gráfico parecido al ejemplo
plot(var_movil,
     type = "l",
     col  = "red",
     lwd  = 2,
     main = "Varianza móvil (12 meses)",
     ylab = "Varianza",
     xlab = "Tiempo")

```
## Medias Móviles

```{r,warning=FALSE}
library(forecast)

# 1. Transformamos la serie a escala logarítmica
ts_log = log(ts_total)

# 2. Calculamos las medias móviles sobre la serie logarítmica
ma3_log  = ma(ts_log, order = 3)
ma6_log  = ma(ts_log, order = 6)
ma12_log = ma(ts_log, order = 12)

# 3. Deshacemos el cambio usando la función exponencial exp()
ma3_fitted  = exp(ma3_log)
ma6_fitted  = exp(ma6_log)
ma12_fitted = exp(ma12_log)
```

```{r}
max_y = max(ts_total, na.rm = TRUE)
limites_y = c(0, max_y * 1.5)

plot(ts_total, 
     main = "Medias Móviles: Serie Completa (Transformación Logarítmica)", 
     ylab = "",       
     xlab = "Tiempo", 
     col = "grey70", 
     lwd = 1,
     ylim = limites_y,
     las = 1)         

# Añadimos las líneas de las medias móviles
lines(ma3_fitted, col = "blue", lwd = 2)      
lines(ma6_fitted, col = "red", lwd = 2)      
lines(ma12_fitted, col = "darkgreen", lwd = 2)  

# 4. Leyenda unificada
legend("topleft", 
       legend = c("Serie Original", "MA(3)", "MA(6)", "MA(12)"), 
       col = c("grey70", "blue", "red", "darkgreen"), 
       lwd = 2, 
       bty = "n", 
       cex = 0.8)
```
##Modelo SES, Holt y Holt-Winter
```{r,warning=FALSE}
# --- Preparación ---
ts_log = log(ts_total)

# ====== SES (Simple Exponential Smoothing) ======
# Al ser logarítmico, suaviza las tasas de variación
ses_log_model = HoltWinters(ts_log, beta = FALSE, gamma = FALSE)

# Revertimos la escala de los valores ajustados usando exp()
ses_fitted_log = exp(ses_log_model$fitted[, 1])

# ====== Modelo de Holt (Tendencia Lineal) ======
# Al aplicar logaritmo, el crecimiento exponencial se vuelve lineal
holt_log_model = HoltWinters(ts_log, gamma = FALSE)

# Revertimos la escala
holt_fitted_log = exp(holt_log_model$fitted[, 1])

# Holt-Winters multiplicativo vía log
log_ts = log(ts_total)
hw_log = HoltWinters(log_ts, seasonal = "additive")
hw_fitted = exp(hw_log$fitted[,1])
```


```{r}
rango_original = range(c(as.numeric(ts_total), as.numeric(ses_fitted_log)), na.rm = TRUE)
limites_ses_ampliados = c(rango_original[1], rango_original[2] * 1.3)

plot(ts_total,
     main = "Suavizado Exponencial Simple (SES)-Serie Completa",
     ylab = "Total", 
     xlab = "Tiempo",
     col = "black", 
     lwd = 2,
     ylim = limites_ses_ampliados)

lines(ses_fitted_log, col = "blue", lwd = 2)

legend("topleft",
       legend = c("Serie original", "SES (Log)"),
       col = c("black", "blue"),
       lwd = 2, 
       bty = "n",
       inset = c(0.02, 0.02))
```


```{r}
rango_holt = range(c(as.numeric(ts_total), as.numeric(holt_fitted_log)), na.rm = TRUE)
limites_holt_ampliados = c(rango_holt[1], rango_holt[2] * 1.3)

plot(ts_total,
     main = "Modelo de Holt (tendencia)",
     ylab = "Total", xlab = "Tiempo",
     col = "black", lwd = 2,
     ylim = limites_holt_ampliados)

lines(holt_fitted_log, col = "red", lwd = 2)

legend("topleft",
       legend = c("Serie original", "Holt (Log)"),
       col = c("black", "red"),
       lwd = 2, 
       bty = "n",
       inset = c(0.02, 0.02))
```


```{r}
limites_hw = range(c(as.numeric(ts_total), as.numeric(hw_fitted)), na.rm = TRUE)

plot(ts_total,
     main = "Modelo de Holt-Winters (tendencia + estacionalidad)",
     ylab = "Total", xlab = "Tiempo",
     col = "black", lwd = 2, 
     ylim=limites_hw)

lines(hw_fitted, col = "darkgreen", lwd = 2)

legend("topleft",
       legend = c("Serie original", "Holt-Winters"),
       col = c("black", "darkgreen"),
       lwd = 2,
       bty = "n")
```
##Predicciones Holt Winter
```{r}
library(forecast)

pred_log = predict(hw_log, n.ahead = 12, prediction.interval = TRUE, level = 0.95)
hw_pronostico = forecast(hw_log, h = 12)

plot(hw_pronostico, main = "Pronóstico Logarítmico Modelo Holt-Winter")
```

```{r}
plot(hw_log, 
     predicted.values = pred_log, 
     main = "Holt-Winters filtering (Log Scale)",
     ylab = "Log(Turistas)", 
     xlab = "Tiempo",
     col = "black",           # Serie histórica
     col.predicted = "blue",  
     lwd = 1)
abline(v = tail(time(ts_total), 1), lty = 3, col = "gray40")
```

```{r}
#Pasamos a escala original
pred_nivel = exp(pred_log)
hw_pronostico$mean  = exp(hw_pronostico$mean)
hw_pronostico$lower = exp(hw_pronostico$lower)
hw_pronostico$upper = exp(hw_pronostico$upper)

plot(hw_pronostico,
     main = "Pronóstico Holt-Winters (Escala Original)",
     ylab = "Turistas")
lines(ts_total, lwd = 2)
```


```{r,warning=FALSE}
# Métricas de error (escala original)
# Funciones de error
MAE  = function(y, yhat) mean(abs(y - yhat))
RMSE = function(y, yhat) sqrt(mean((y - yhat)^2))
MAPE = function(y, yhat) mean(abs((y - yhat) / y)) * 100

# Serie logarítmica
ts_log = log(ts_total)

# Ajustes
# SES
fit_ses = HoltWinters(ts_log, beta = FALSE, gamma = FALSE)
ajuste_ses = exp(fit_ses$fitted[,1])

# Holt
fit_holt = HoltWinters(ts_log, gamma = FALSE)
ajuste_holt = exp(fit_holt$fitted[,1])

# Holt-Winters
fit_hw = HoltWinters(ts_log)
ajuste_hw = exp(fit_hw$fitted[,1])


# Alinear serie observada
y_real = window(ts_total, start = start(ajuste_hw))

# Métricas
resultados = data.frame(
  Modelo = c("SES", "Holt", "Holt-Winters"),
  MAE = c(
    MAE(y_real, ajuste_ses),
    MAE(y_real, ajuste_holt),
    MAE(y_real, ajuste_hw)
  ),
  RMSE = c(
    RMSE(y_real, ajuste_ses),
    RMSE(y_real, ajuste_holt),
    RMSE(y_real, ajuste_hw)
  ),
  MAPE = c(
    MAPE(y_real, ajuste_ses),
    MAPE(y_real, ajuste_holt),
    MAPE(y_real, ajuste_hw)
  )
)

# Mostrar resultados
library(knitr)
kable(print(resultados))

```