---
title: "Modelo ARIMA"
author: "José Ramón Mena Pérez"
date: "2026-01-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Carga y Preparación de Datos
```{r}
# 1. Lectura y formateo de fechas
df = read.csv("Turistas_Limpio.csv")
df$Fecha = as.Date(paste0(substr(df$Periodo,1,4), "-", substr(df$Periodo,6,7), "-01"))

# 2. Creación de la Serie Temporal Original
turistas = ts(df$Total,
               start = c(as.numeric(substr(df$Periodo[1],1,4)),
                         as.numeric(substr(df$Periodo[1],6,7))),
               frequency = 12)

# 3. Transformaciones para Estacionariedad (Serie Completa)
z_t = log(turistas)                               
z_diff = diff(z_t, differences = 1)              
z_diff_season = diff(z_diff, lag = 12, differences = 1)
```

##Visualización de Transformaciones (Serie Completa)
```{r}
plot(z_t, 
     main = "Serie transformada logarítmicamente", 
     ylab = "log(Turistas)", 
     col = "#2E86C1", lwd = 2)

```

```{r}
plot(z_diff, 
     main = "Diferencia Regular (d=1) sobre log(Turistas)", 
     ylab = "diff(log)", 
     col = "#E74C3C", lwd = 1.5)
abline(h = 0, col = "gray40", lty = 2)
```

```{r}
plot(z_diff_season, 
     main = "Diferencia Estacional (D=1) sobre d=1", 
     ylab = "diff_seasonal", 
     col = "#27AE60", lwd = 1.5)
abline(h = 0, col = "gray40", lty = 2)
```
##Análisis Post-COVID (Filtro y Estacionariedad)

```{r}
# 1. Filtrar solo datos post-COVID (desde 2022M01)
df_post = df[df$Fecha >= as.Date("2022-01-01"), ]

turistas_post = ts(df_post$Total,
                    start = c(2022, 1),
                    frequency = 12)

# 2. Aplicación de diferencias en serie aditiva (Post-COVID)
z_post = turistas_post
z_post_diff = diff(z_post, differences = 1)
z_post_diff_season = diff(z_post_diff, lag = 12, differences = 1)
```

```{r}
plot(z_post, main = "Serie Post-Covid",
     ylab = "Turistas", xlab = "Tiempo", col = "blue", lwd = 2)
```

```{r}
plot(z_post_diff, main = "Diferencia Regular (d=1)",
     ylab = "diff(Turistas)", xlab = "Tiempo", col = "red")
```

```{r}
plot(z_post_diff_season, main = "Diferencia Estacional (D=1)",
     ylab = "diff(diff)", xlab = "Tiempo", col = "darkgreen")
```
##Identificación del Modelo: ACF y PACF
```{r}
# 1. Gráfico ACF
acf(z_post_diff_season,
    lag.max = 36,
    ylim = c(-1, 1),
    main = "ACF Post-Covid (d=1, D=1)",
    col = "#2E86C1")
```

```{r}
# 2. Gráfico PACF
pacf(z_post_diff_season,
     lag.max = 36,
     ylim = c(-1, 1),
     main = "PACF Post-Covid (d=1, D=1)",
     col = "#2E86C1")
```
##Ajuste del Modelo ARIMA (autoarima)
```{r}
library(forecast)
library(knitr)

# Ajuste automático del mejor modelo SARIMA
fit_auto_post = auto.arima(turistas_post,
                            seasonal = TRUE,
                            lambda = "auto") 

# Extraer valores para validación
fit_final = fit_auto_post
res = residuals(fit_final)
fit_final
pred=predict(fit_final, n.ahead = 12)
tail(res,1)
yhat = InvBoxCox(pred$pred, lambda = 1.139516)  # escala original
tabla <- data.frame(
  Z_hat = as.numeric(pred$pred),  # transformado
  Y_hat = as.numeric(yhat)         # escala original
)

kable(tabla)
```
```{r}
lambda_val = fit_final$lambda

yhat = InvBoxCox(pred$pred, lambda = lambda_val)

lim_sup = InvBoxCox(pred$pred + 1.96 * pred$se, lambda = lambda_val)
lim_inf = InvBoxCox(pred$pred - 1.96 * pred$se, lambda = lambda_val)

limite_superior_grafico = max(turistas_post, lim_sup)
limite_inferior_grafico = min(turistas_post, lim_inf)

ts.plot(turistas_post, yhat, 
        lty = c(1,3), 
        col = c("black", "blue"),
        main = "Predicción ARIMA(0,1,1)(0,1,0)12",
        ylab = "Total Turistas",
        xlab = "Tiempo",
        ylim = c(limite_inferior_grafico, limite_superior_grafico))

lines(lim_sup, col = "red", lty = 2)
lines(lim_inf, col = "red", lty = 2)

legend("topleft", 
       legend = c("Histórico", "Predicción", "IC 95%"),
       col = c("black", "blue", "red"), 
       lty = c(1, 3, 2), 
       bty = "n")
```




##Diagnóstico de Residuos
```{r}
# 1. Residuos en el tiempo
plot(res, type = "l", main = "Residuos en el tiempo", ylab = "Residuos")
abline(h = 0, col = "red")
```
```{r}
# 2. Residuos estandarizados
res_std = res / sd(res)
plot(res_std, type = "l", ylim = c(-4, 4), main = "Residuos Estandarizados")
abline(h = c(-2, 0, 2), col = c("blue", "red", "blue"), lty = c(2, 1, 2), lwd = 1)
```
```{r}
# 3. ACF de residuos
acf(res, lag.max = 36, main = "ACF de Residuos", col = "gray40")
```
```{r}
# 4. PACF de residuos
pacf(res, lag.max = 36, main = "PACF de Residuos", col = "gray40")
```

##Análisis de Normalidad

```{r}
# 1. Histograma de Residuos
hist(res, breaks = 12, main = "Distribución de Residuos", 
     xlab = "Residuos", col = "steelblue", border = "white")
```

```{r}
# 2. QQ-Plot de Residuos
qqnorm(res, main = "QQ-plot de Residuos")
qqline(res, col = "red", lwd = 2)
```

```{r}
# 3. Test Estadístico de Normalidad (Shapiro-Wilk)
test_shapiro = shapiro.test(res)

# Creamos un dataframe para que kable pueda renderizarlo
tabla_shapiro = data.frame(
  Estadistico = test_shapiro$statistic,
  P_Valor = test_shapiro$p.value,
  Metodo = test_shapiro$method
)

library(knitr)
kable(tabla_shapiro, 
      digits = 4, 
      caption = "Resultado del Test de Normalidad de Shapiro-Wilk",
      col.names = c("Estadístico W", "p-valor", "Método"))
```

```{r}
# Cálculo del RMSE en escala original
rmse_arima_ok = sqrt(mean((turistas_post - fitted(fit_final))^2, na.rm = TRUE))

# Visualización del ajuste
plot(turistas_post, lwd = 2, main = "Ajuste del Modelo ARIMA: Post-COVID", ylab = "Turistas", las = 1)
lines(fitted(fit_final), col = "red", lty = 2, lwd = 2)

legend("topleft", legend = c("Real", "Ajustado ARIMA"), 
       col = c("black", "red"), lwd = 2, lty = c(1, 2), bty = "n")

cat("El RMSE del modelo ARIMA final es:", round(rmse_arima_ok, 2))
```

```{r}
## Predicción a Futuro
# 1. Generar el pronóstico para los próximos 12 meses
pronostico_arima = forecast(fit_final, h = 12)

# 2. Mostrar los valores predichos en una tabla estética
# Usamos zoo para convertir el tiempo de la serie en fechas legibles
tiempos = zoo::as.yearmon(time(pronostico_arima$mean))

tabla_pronostico = data.frame(
  Mes = as.character(tiempos),
  Prediccion = as.numeric(pronostico_arima$mean),
  Lim_Inf_95 = as.numeric(pronostico_arima$lower[,2]),
  Lim_Sup_95 = as.numeric(pronostico_arima$upper[,2])
)

library(knitr)
kable(tabla_pronostico, 
      digits = 2, 
      caption = "Valores Predichos para los próximos 12 meses (Intervalo de Confianza 95%)",
      col.names = c("Mes/Año", "Valor Predicho", "Lím. Inf (95%)", "Lím. Sup (95%)"))
```